Prepare to be gim compliant

diff --git a/build/ux430ua-jack-volume b/build/ux430ua-jack-volume
--- a/build/ux430ua-jack-volume
+++ b/build/ux430ua-jack-volume
@@ -18,7 +18,7 @@ SW_REQUIRED='command echo [ id hda-verb'
 for i in $SW_REQUIRED; do
     # software is missing if at least one piece of software is missing
     if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software '$i' is missing, action canceled." >&2
+        echo "$0: Required software '$i' is missing." >&2
         # the program dependencies may be missing
         if [ "$i" = hda-verb ]; then
             echo 'POSSIBLE SOLUTIONS:
@@ -35,7 +35,7 @@ done
 # the current version of the program
 VERSION=1.3.0
 
-HELP_MESSAGE="Usage: $0 [OPTION]...
+HELP_MESSAGE="USAGE: $0 [OPTION]...
 
 OPTION:
   -help     show this help and exit
@@ -70,7 +70,8 @@ for i in "$@"; do
             ;;
         *)
             echo "$0: The option '$i' was not recognized.
-Try '$0 -help' for more information." >&2
+POSSIBLE SOLUTIONS:
+  * use the '$0 -help' command for more information" >&2
             exit 1
             ;;
     esac
@@ -82,7 +83,7 @@ done
 
 # check if character device file for sound driving exists
 if [ ! -c /dev/snd/hwC0D0 ]; then
-    echo "$0: Character device file '/dev/snd/hwC0D0' doesn't exist, action canceled.
+    echo "$0: Character device file '/dev/snd/hwC0D0' doesn't exist.
 POSSIBLE CAUSES:
   * ALSA framework is not used on this system" >&2
     exit 1
@@ -90,7 +91,7 @@ fi
 
 # check if running as root
 if [ "$(id -u)" -ne 0 ]; then
-    echo "$0: Please run as root, action canceled." >&2
+    echo "$0: Please run as root." >&2
     exit 1
 fi
 
diff --git a/make/install b/make/install
--- a/make/install
+++ b/make/install
@@ -22,7 +22,7 @@ SW_REQUIRED='command echo [ id grep chmod sed cd mkdir cp realpath head'
 for i in $SW_REQUIRED; do
     # software is missing if at least one piece of software is missing
     if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software '$i' is missing, installation canceled." >&2
+        echo "$0: Required software '$i' is missing." >&2
         exit 1
     fi
 done
@@ -49,7 +49,7 @@ INSTALL_DIR_ESCAPED="$(echo "$INSTALL_DIR" | sed -E -e 's|/|\\/|g')"
 
 # check if arguments passed
 if [ -z "$1" ] || [ -z "$2" ]; then
-    echo "$0: Please supply non-empty arguments, installation canceled." >&2
+    echo "$0: Please supply non-empty arguments." >&2
     exit 1
 fi
 
@@ -60,23 +60,29 @@ if [ -f "$CONFIG_DIR/install-dir" ]; then
     installed_dir="$(cd "$CONFIG_DIR/" && realpath -m "$(head -n 1 install-dir)")"
 
     if [ "$INSTALL_DIR" = "$installed_dir" ]; then
-        echo "The program is already installed in '$installed_dir/', installation canceled."
+        echo "The program is already installed in '$installed_dir/'."
         exit 0
     else
-        echo "$0: The program is already installed in '$installed_dir/', installation canceled." >&2
+        echo "$0: The program is already installed in '$installed_dir/'.
+POSSIBLE SOLUTIONS:
+  * uninstall it and install it again to the desired directory" >&2
         exit 1
     fi
 fi
 
 # check if given installation directory exists
 if [ ! -d "$INSTALL_DIR/" ]; then
-    echo "$0: '$INSTALL_DIR/' doesn't exist, installation canceled." >&2
+    echo "$0: Given installation directory '$INSTALL_DIR/' doesn't exist.
+POSSIBLE SOLUTIONS:
+  * create '$INSTALL_DIR/' and repeat the action" >&2
     exit 1
 fi
 
 # check if ux430ua-jack-volume file exists
 if [ ! -f "$1/ux430ua-jack-volume" ]; then
-    echo "$0: '$1/ux430ua-jack-volume' does not exist, installation canceled." >&2
+    echo "$0: '$1/ux430ua-jack-volume' does not exist.
+POSSIBLE SOLUTIONS:
+  * download the project again and repeat the action" >&2
     exit 1
 fi
 
@@ -86,7 +92,7 @@ fi
 
 # check if running as root
 if [ "$(id -u)" -ne 0 ]; then
-    echo "$0: Please run as root, installation canceled." >&2
+    echo "$0: Please run as root." >&2
     exit 1
 fi
 
@@ -115,11 +121,16 @@ sed -i -E -e '/'"$CONTAINS_EXIT_0"'/{s//'"'$INSTALL_DIR_ESCAPED"'\/ux430ua-jack-
 echo "#!/bin/sh
 
 '$INSTALL_DIR/ux430ua-jack-volume'" > /lib/systemd/system-sleep/ux430ua-jack-volume-caller &&
-chmod a+x /lib/systemd/system-sleep/ux430ua-jack-volume-caller || exit 1
+chmod a+x /lib/systemd/system-sleep/ux430ua-jack-volume-caller || {
+    echo "$0: It wasn't possible to finish the installation.
+POSSIBLE SOLUTIONS:
+  * free up some storage space
+  * contact a gim developer" >&2
+    exit 1
+}
 
 # apply the changes immediately (it may not be successful because the program dependencies may be missing)
-echo 'Applying changes.'
+echo 'Trying to apply the changes immediately.'
 "$INSTALL_DIR"/ux430ua-jack-volume
 
-# final message
-echo 'Installation finished successfully!'
+exit 0
diff --git a/make/install-deps b/make/install-deps
--- a/make/install-deps
+++ b/make/install-deps
@@ -18,7 +18,7 @@ SW_REQUIRED='command echo id apt'
 for i in $SW_REQUIRED; do
     # software is missing if at least one piece of software is missing
     if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software '$i' is missing, installation of dependencies canceled." >&2
+        echo "$0: Required software '$i' is missing." >&2
         exit 1
     fi
 done
@@ -29,12 +29,9 @@ done
 
 # check if running as root
 if [ "$(id -u)" -ne 0 ]; then
-    echo "$0: Please run as root, installation of dependencies canceled." >&2
+    echo "$0: Please run as root." >&2
     exit 1
 fi
 
 # install the following package to control the jack sound volume level
 apt install alsa-tools -y || exit 1
-
-# final message
-echo 'Installation of dependencies finished successfully!'
