Add support for TAB completion for BASH

diff --git a/make/deploy b/make/deploy
--- a/make/deploy
+++ b/make/deploy
@@ -121,6 +121,19 @@ POSSIBLE SOLUTIONS:
     exit 1
 }
 
+# check if bash shell is used on this system
+if grep -q -E -e '^/bin/bash$' /etc/shells; then
+    # set up TAB completion for bash shell
+    mkdir -p /etc/bash_completion.d/ &&
+    cp "$SRC_DIR/ux430ua-jack-volume_completion" /etc/bash_completion.d/ || {
+        echo "$0: Can't set up TAB completion.
+POSSIBLE SOLUTIONS:
+  * Uninstall ux430ua-jack-volume and install it again.
+  * Free up some storage space, uninstall ux430ua-jack-volume and install it again.
+  * Contact a ux430ua-jack-volume developer." >&2
+    }
+fi
+
 # try to apply all changes immediately (if install-deps hasn't been run before, it may be unsuccessful)
 "$INSTALL_DIR"/ux430ua-jack-volume > /dev/null 2>/dev/null || {
     echo "$0: Can't apply the changes immediately.
