Change messages in install-deps

diff --git a/make/install-deps b/make/install-deps
--- a/make/install-deps
+++ b/make/install-deps
@@ -18,7 +18,7 @@ SW_REQUIRED='echo id apt'
 for i in $SW_REQUIRED; do
     # software is missing if at least one piece of software is missing
     if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software '$i' is missing, dependency installation canceled." >&2
+        echo "$0: Required software '$i' is missing, installation of dependencies canceled." >&2
         exit 1
     fi
 done
@@ -29,7 +29,7 @@ done
 
 # check if running as root
 if [ "$(id -u)" -ne 0 ]; then
-    echo "$0: Please run as root, dependency installation canceled." >&2
+    echo "$0: Please run as root, installation of dependencies canceled." >&2
     exit 1
 fi
 
@@ -37,4 +37,4 @@ fi
 apt install alsa-tools -y || exit 1
 
 # final messaged
-echo 'Dependency installation finished successfully!'
+echo 'Installation of dependencies finished successfully!'
