Update code style

diff --git a/src/ux430ua-jack-volume b/src/ux430ua-jack-volume
--- a/src/ux430ua-jack-volume
+++ b/src/ux430ua-jack-volume
@@ -13,10 +13,10 @@
 SW_REQUIRED='command echo [ id hda-verb'
 
 # check if some software is missing
-for i in $SW_REQUIRED; do
+for sw in $SW_REQUIRED; do
     # software is missing if at least one piece of software is missing
-    if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software $i is missing." >&2; exit 1
+    if ! command -v "$sw" > /dev/null; then
+        echo "$0: Required software $sw is missing." >&2; exit 1
     fi
 done
 
@@ -45,8 +45,8 @@ github.com/dominiksalvet/ux430ua-jack-volume"
 #-------------------------------------------------------------------------------
 
 # processing each parameter separately
-for i in "$@"; do
-    case "$i" in
+for opt in "$@"; do
+    case "$opt" in
         -help) echo "$HELP_MESSAGE"; exit ;;
         -about) echo "$ABOUT_MESSAGE"; exit ;;
         -version) echo "$VERSION"; exit ;;
